import type {Metadata} from "next";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import "./globals.css";
import Navbar from "~/components/Navbar";
import {ConfigProvider} from "antd";

export const metadata: Metadata = {
  title: "IoT system by Duy Luan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-logo">
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: "Permanent Marker, cursive",
              },
              components: {
                Table: {
                  cellFontSize: 16,
                },
              },
            }}
          >
            <Navbar />
            <div className="mt-8 opacity-90">{children}</div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
